<?php
return [
	'SetupLoader' => 'setup/inc/SetupLoader.php',
	'ParseSqlFile' => 'setup/inc/ParseSqlFile.php',
	'SetupModel' => 'setup/inc/SetupModel.php',
	'SetupPageRenderer' => 'setup/inc/SetupPageRenderer.php',
	'SetupModelUpdate' => 'setup/inc/SetupModelUpdate.php',
	'SetupView' => 'setup/inc/SetupView.php',
	'SetupAction' => 'setup/inc/SetupAction.php',
	'SetupView_license' => 'setup/inc/view/SetupView_license.php',
	'SetupView_db' => 'setup/inc/view/SetupView_db.php',
	'SetupView_user' => 'setup/inc/view/SetupView_user.php',
	'SetupView_config' => 'setup/inc/view/SetupView_config.php',
	'SetupView_setting' => 'setup/inc/view/SetupView_setting.php',
	'SetupView_install' => 'setup/inc/view/SetupView_install.php',
	'SetupView_upgrade' => 'setup/inc/view/SetupView_upgrade.php',
	'SetupView_licence' => 'setup/inc/view/SetupView_licence.php',
	'SetupView_update_email' => 'setup/inc/view/SetupView_update_email.php',
	'SetupView_setup' => 'setup/inc/view/SetupView_setup.php',
	'SetupView_lang' => 'setup/inc/view/SetupView_lang.php',
	'SetupView_initial' => 'setup/inc/view/SetupView_initial.php',
	'SetupView_index' => 'setup/inc/view/SetupView_index.php',
	'SetupView_success' => 'setup/inc/view/SetupView_success.php',
	'SetupView_library' => 'setup/inc/view/SetupView_library.php',
	'SetConfiguration' => 'setup/inc/SetConfiguration.php',
	'SetupController' => 'setup/inc/SetupController.php',
	'SetupModelUpgrade_80' => 'setup/inc/SetupModelUpgrade_80.php',
	'_SetupModelInstall' => 'setup/inc/_SetupModelInstall.php',
	'SetupModelUpgrade' => 'setup/inc/SetupModelUpgrade.php',
	'CheckConfiguration' => 'setup/inc/CheckConfiguration.php',
	'SetupAction_upgrade' => 'setup/inc/action/SetupAction_upgrade.php',
	'SetupAction_license' => 'setup/inc/action/SetupAction_license.php',
	'SetupAction_install' => 'setup/inc/action/SetupAction_install.php',
	'SetupAction_setup' => 'setup/inc/action/SetupAction_setup.php',
	'SetupAction_setting' => 'setup/inc/action/SetupAction_setting.php',
	'SetupAction_licence' => 'setup/inc/action/SetupAction_licence.php',
	'SetupAction_update' => 'setup/inc/action/SetupAction_update.php',
	'SetupAction_db' => 'setup/inc/action/SetupAction_db.php',
	'SetupAction_library' => 'setup/inc/action/SetupAction_library.php',
	'SetupAction_user' => 'setup/inc/action/SetupAction_user.php',
	'SetupAction_index' => 'setup/inc/action/SetupAction_index.php',
	'SetupAction_initial' => 'setup/inc/action/SetupAction_initial.php',
	'SetupAction_config' => 'setup/inc/action/SetupAction_config.php',
	'SetupAction_lang' => 'setup/inc/action/SetupAction_lang.php',
	'SetupAction_success' => 'setup/inc/action/SetupAction_success.php',
	'SetupAction_default' => 'setup/inc/action/SetupAction_default.php'
	];
?>